# Generated by Django 4.0.4 on 2022-07-16 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityA', models.CharField(max_length=255)),
                ('entityB', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dataset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
