# Generated by Django 4.0.4 on 2022-07-26 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_entity_relation_semantictype_triple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triple',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
