# Generated by Django 4.0.4 on 2022-07-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_entity_user_alter_relation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semantictype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
