# Generated by Django 4.1 on 2022-09-09 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_entity_name_alter_triple_entitya_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='semantictype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='triple',
            options={'ordering': ('relation',)},
        ),
        migrations.AlterField(
            model_name='entity',
            name='semantic_type',
            field=models.ManyToManyField(blank=True, to='users.semantictype'),
        ),
        migrations.CreateModel(
            name='ConfirmedTriple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_entA', to='users.entity')),
                ('entityB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.entity')),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_entB', to='users.relation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('relation',),
            },
        ),
        migrations.CreateModel(
            name='ConfirmedSemanticType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ConfirmedRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ConfirmedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('semantic_type', models.ManyToManyField(blank=True, to='users.semantictype')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
