# Generated by Django 4.1 on 2022-09-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_entity_options_alter_relation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmedrelation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='confirmedsemantictype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='confirmedtriple',
            name='entityA',
        ),
        migrations.RemoveField(
            model_name='confirmedtriple',
            name='entityB',
        ),
        migrations.RemoveField(
            model_name='confirmedtriple',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='confirmedtriple',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConfirmedEntity',
        ),
        migrations.DeleteModel(
            name='ConfirmedRelation',
        ),
        migrations.DeleteModel(
            name='ConfirmedSemanticType',
        ),
        migrations.DeleteModel(
            name='ConfirmedTriple',
        ),
    ]
