# Generated by Django 4.1 on 2022-09-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_confirmedrelation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semantictype',
            name='verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
