# Generated by Django 4.1 on 2022-09-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_semantictype_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semantictype',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
