# Generated by Django 4.1 on 2022-09-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_semantictype_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
