# Generated by Django 4.1 on 2022-09-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_relation_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='triple',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
