# Generated by Django 4.1 on 2022-09-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_triple_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='semantictype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='triple',
            name='entityA',
        ),
        migrations.RemoveField(
            model_name='triple',
            name='entityB',
        ),
        migrations.RemoveField(
            model_name='triple',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='triple',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdataset',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.DeleteModel(
            name='SemanticType',
        ),
        migrations.DeleteModel(
            name='Triple',
        ),
        migrations.DeleteModel(
            name='UserDataset',
        ),
    ]
