# Generated by Django 4.1 on 2022-09-20 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AuditTriple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityA', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
                ('entityB', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('entityA_types', models.ManyToManyField(blank=True, related_name='entityA_types', to='Audit.type')),
                ('entityB_types', models.ManyToManyField(blank=True, related_name='entityB_types', to='Audit.type')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
