# Generated by Django 4.1 on 2022-09-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittriple',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
