# Generated by Django 4.1 on 2022-09-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0003_alter_audittriple_id_alter_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
