# Generated by Django 4.1 on 2022-09-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0004_alter_type_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audittriple',
            options={'ordering': ('relation',)},
        ),
    ]
