# Generated by Django 4.1 on 2022-10-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0008_audittriple_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittriple',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Enter a optional reason for un verifing', verbose_name='comments'),
            preserve_default=False,
        ),
    ]
