# Generated by Django 4.0.4 on 2022-05-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityA', models.CharField(max_length=255)),
                ('entityB', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
            ],
        ),
    ]
