# Generated by Django 4.0.4 on 2022-06-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityA', models.CharField(max_length=255)),
                ('entityB', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=255)),
            ],
        ),
    ]
