# Generated by Django 4.1 on 2022-09-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadData', '0003_relation_semantictype_entity_alter_triple_entitya_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triple',
            name='entityA',
        ),
        migrations.RemoveField(
            model_name='triple',
            name='entityB',
        ),
        migrations.RemoveField(
            model_name='triple',
            name='relation',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
        migrations.DeleteModel(
            name='SemanticType',
        ),
        migrations.DeleteModel(
            name='Triple',
        ),
    ]
